repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: helmlint

  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.3
    hooks:
      - id: go-fmt-import
      - id: go-vet
      - id: go-lint
      - id: go-unit-tests
      - id: go-static-check

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.13.1
    hooks:
      - id: helm-docs
        files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        stages: [ commit ]
