apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "runtime-registry-config.fullname" . }}
  labels:
    {{- include "runtime-registry-config.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "runtime-registry-config.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "runtime-registry-config.selectorLabels" . | nindent 8 }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
    {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "runtime-registry-config.serviceAccountName" . }}
      hostPID: true
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
              - SYS_ADMIN
              - SYS_CHROOT
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: LOG_LEVEL
            value: {{ .Values.logLevel }}
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - mountPath: /run/dbus
            name: dbus
          - mountPath: /etc/containers
            name: crio-config
          - mountPath: /run/systemd
            name: systemd
      volumes:
        - hostPath:
            path: /etc/containers
            type: Directory
          name: crio-config
        - hostPath:
            path: /run/dbus
            type: Directory
          name: dbus
        - hostPath:
            path: /run/systemd
            type: Directory
          name: systemd
