apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "runtime-registry-config.fullname" . }}
  labels:
    {{- include "runtime-registry-config.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
